services:
  api-http:
    environment:
      - PII_EMBED_DEVICE=cuda
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES:-compute,utility}
    deploy: &gpu-deploy
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${PII_GPU_COUNT:-all}
              capabilities: [gpu]

  api-https:
    environment:
      - PII_EMBED_DEVICE=cuda
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES:-compute,utility}
    deploy: *gpu-deploy

  api-grpc-1:
    environment:
      - PII_EMBED_DEVICE=cuda
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES:-compute,utility}
    deploy: *gpu-deploy

  api-grpc-2:
    environment:
      - PII_EMBED_DEVICE=cuda
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES:-compute,utility}
    deploy: *gpu-deploy

  api-grpc-3:
    environment:
      - PII_EMBED_DEVICE=cuda
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES:-compute,utility}
    deploy: *gpu-deploy
